"""initial

Revision ID: 4413eeb45d01
Revises: 
Create Date: 2026-04-17 09:42:40.398771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4413eeb45d01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wcms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('will', sa.Text(), nullable=True),
    sa.Column('can', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'period', name='uq_wcm_member_period')
    )
    op.create_table('musts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wcm_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('sub_theme', sa.String(length=200), nullable=True),
    sa.Column('mission', sa.String(length=300), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('order_', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wcm_id'], ['wcms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('musts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_musts_wcm_id'), ['wcm_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('conversation_location', sa.String(length=1000), nullable=True),
    sa.Column('materials_url', sa.Text(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['musts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_mission_id'), ['mission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_mission_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_member_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('musts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_musts_wcm_id'))

    op.drop_table('musts')
    op.drop_table('wcms')
    op.drop_table('members')
    # ### end Alembic commands ###
